import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Teko, Roboto_Flex } from 'next/font/google'

const teko = Teko({
  subsets: ['latin'],
  variable: '--font-teko'
})

const roboto = Roboto_Flex({
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${teko.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
