import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const EuroEx = localFont({
  src: "./fonts/EurostileExtd.otf",
  variable: "--font-euro-ex",
});

const Sternbach = localFont({
  src: "./fonts/Sternbach.otf",
  variable: "--font-sternbach",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${EuroEx.variable} ${Sternbach.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
