name: CI

on:
  push:
    branches: [feat/CD]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.name "fightcentral"
            git config --global user.email "fightcentral667@gmail.com"
            git config --global credential.helper cache
            git clone https://${{secrets.API_TOKEN_GITHUB}}@github.com/fightcentral6/fightcentral-web web
            rsync -av . web --exclude web --exclude .git --exclude .github
            cd web
            git pull
            git add .
            git commit -m "Deploy"
            git push origin main